### ISSUE TITLE
Venue map incorrect?

### ISSUE THREAD

**Issue by IndianGuru** [emergingtechs/devopsdays#12]
http://devopsdaysindia.org/#venue

The Venue would be Hotel Royal Orchid but the map shows Hotel Royal Orchid Central - are they the same, at least the addresses are different.

**Comment by wallydrag** [comment]
hello @IndianGuru, the map shows Hotel Royal Orchid, which i guess is the correct venue. Can you share the exact address to remove the confusion?
<img width="1280" alt="screen shot 2016-07-13 at 6 41 33 pm" src="https://cloud.githubusercontent.com/assets/7490092/16804517/dd14f162-4929-11e6-84a6-9a4e30027336.png">
. I also checked the mail thread with Royal Orchid and the address on it matches the one on devopsdays website. cc @SinisterLight

**Comment by IndianGuru** [comment]
![clipboard01](https://cloud.githubusercontent.com/assets/178281/16823778/1a738758-4984-11e6-94c5-e85691dcb2b6.jpg)

I see Royal Orchid Central even on multiple browser refreshes - strange.

**Comment by IndianGuru** [comment]
Now fixed. Closing this issue.
