### ISSUE TITLE
Change URL of Sponsor Aspose

### ISSUE THREAD

**Issue by IndianGuru** [emergingtechs/devopsdays#17]
As mentioned in my earlier issue the URL for Aspose should be -
http://www.aspose.com/?utm_source=devopdays&utm_medium=banner&utm_campaign=devopdays

**Comment by wallydrag** [comment]
PR raised. Although, just out of curiosity, why do we want this particular url to be in place when just aspose.com lands us on the same page?

**Comment by SinisterLight** [comment]
@wallydrag So there analytics can track from where the traffic is coming from
