### ISSUE TITLE
Add website link to description

### ISSUE THREAD

**Issue by budhrg** [emergingtechs/devopsdays#46]
Hi,

I think it would be better if we add website link http://devopsdaysindia.org to description. One can navigate to site using repo too.

**Comment by IndianGuru** [comment]
Which description?

**Comment by budhrg** [comment]
@IndianGuru Please check screenshot below sir

![screenshot from 2016-10-05 10-41-14](https://cloud.githubusercontent.com/assets/1132451/19101747/743ace0e-8ae8-11e6-8cc5-2c4e5f9b53a8.png)

**Comment by IndianGuru** [comment]
Done.
